services:
  nginx:
    image: nginx:alpine
    ports:
      - "11080:80"
      - "11443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/usr/share/nginx/html/frontend
    depends_on:
      - frontend
      - backend
    networks:
      - bowlards-network

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend/Dockerfile
      target: development
    ports:
      - "13000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./docker/frontend/vite.config.ts:/app/vite.config.ts
      - ./docker/frontend/tsconfig.json:/app/tsconfig.json
      - ./docker/frontend/tsconfig.node.json:/app/tsconfig.node.json
      - ./docker/frontend/index.html:/app/index.html
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://localhost:18080/api/v1
      - VITE_FIREBASE_API_KEY=${VITE_FIREBASE_API_KEY}
      - VITE_FIREBASE_AUTH_DOMAIN=${VITE_FIREBASE_AUTH_DOMAIN}
      - VITE_FIREBASE_PROJECT_ID=${VITE_FIREBASE_PROJECT_ID}
      - VITE_FIREBASE_STORAGE_BUCKET=${VITE_FIREBASE_STORAGE_BUCKET}
      - VITE_FIREBASE_MESSAGING_SENDER_ID=${VITE_FIREBASE_MESSAGING_SENDER_ID}
      - VITE_FIREBASE_APP_ID=${VITE_FIREBASE_APP_ID}
    depends_on:
      - backend
    networks:
      - bowlards-network

  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile.dev
    ports:
      - "18080:8000"
    volumes:
      - ./backend:/app
      - /app/__pycache__
      - /app/.pytest_cache
      - /app/.venv
      - ./credentials:/app/credentials
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8000
      - APP_DEBUG=false
      - APP_LOG_LEVEL=INFO
      - APP_LOG_FORMAT=json
      - APP_FIREBASE_PROJECT_ID=${APP_FIREBASE_PROJECT_ID}
      - APP_FIREBASE_CREDENTIALS_PATH=${APP_FIREBASE_CREDENTIALS_PATH}
      - APP_FIREBASE_PRIVATE_KEY=${APP_FIREBASE_PRIVATE_KEY}
      - APP_FIREBASE_CLIENT_EMAIL=${APP_FIREBASE_CLIENT_EMAIL}
    networks:
      - bowlards-network


networks:
  bowlards-network:
    driver: bridge
