# docker-compose.yml
#version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    ports:
      - "28000:8000"  # FastAPI default port
    environment:
      # Firebaseエミュレーター接続設定（APP_プレフィックス必須）
      - APP_FIRESTORE_EMULATOR_HOST=host.docker.internal
      - APP_FIRESTORE_EMULATOR_PORT=8080
      - APP_FIREBASE_AUTH_EMULATOR_HOST=host.docker.internal
      - APP_FIREBASE_AUTH_EMULATOR_PORT=9099
      - APP_FIREBASE_PROJECT_ID=demo-project  # エミュレーター用
      - APP_DEBUG=true
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Linux対応
