version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/usr/share/nginx/html/frontend
      - ./ssl:/etc/nginx/ssl  # SSL証明書
    depends_on:
      - frontend
      - backend
    networks:
      - bowlards-network

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend/Dockerfile
      target: production
    environment:
      - NODE_ENV=production
      - VITE_FIREBASE_API_KEY=${VITE_FIREBASE_API_KEY}
      - VITE_FIREBASE_AUTH_DOMAIN=${VITE_FIREBASE_AUTH_DOMAIN}
      - VITE_FIREBASE_PROJECT_ID=${VITE_FIREBASE_PROJECT_ID}
      - VITE_FIREBASE_STORAGE_BUCKET=${VITE_FIREBASE_STORAGE_BUCKET}
      - VITE_FIREBASE_MESSAGING_SENDER_ID=${VITE_FIREBASE_MESSAGING_SENDER_ID}
      - VITE_FIREBASE_APP_ID=${VITE_FIREBASE_APP_ID}
    networks:
      - bowlards-network

  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8000
      - APP_DEBUG=false
      - APP_LOG_LEVEL=INFO
      - APP_LOG_FORMAT=json
      - APP_FIREBASE_PROJECT_ID=${APP_FIREBASE_PROJECT_ID}
      - APP_FIREBASE_CREDENTIALS_PATH=${APP_FIREBASE_CREDENTIALS_PATH}
      - APP_SECRET_KEY=${APP_SECRET_KEY}
      - APP_ALLOWED_ORIGINS=${APP_ALLOWED_ORIGINS}
    volumes:
      - ./credentials:/app/credentials  # サービスアカウントキー
    networks:
      - bowlards-network

networks:
  bowlards-network:
    driver: bridge
